import ts from 'typescript';
import { readdir, readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const directory = new URL('src/components/', root);
const output = new URL('src/react/generated.ts', root);
const components = [];

function findAttribute(node) {
  let attribute;
  function visit(child) {
    if (ts.isCallExpression(child) && ts.isPropertyAccessExpression(child.expression)
      && ['getAttribute', 'hasAttribute', 'setAttribute', 'toggleAttribute'].includes(child.expression.name.text)
      && child.arguments[0] && ts.isStringLiteral(child.arguments[0])) {
      attribute ??= child.arguments[0].text;
    }
    ts.forEachChild(child, visit);
  }
  visit(node);
  return attribute;
}

for (const entry of (await readdir(directory)).sort()) {
  if (!entry.startsWith('chido-')) continue;
  const file = new URL(`${entry}/${entry}.ts`, directory);
  const content = await readFile(file, 'utf8');
  const source = ts.createSourceFile(fileURLToPath(file), content, ts.ScriptTarget.Latest, true);
  const declaration = source.statements.find(node => ts.isClassDeclaration(node)
    && node.heritageClauses?.some(clause => clause.types.some(type => type.expression.getText(source) === 'HTMLElement')));
  if (!declaration?.name) throw new Error(`Missing HTMLElement class in ${entry}`);
  const properties = [];
  for (const setter of declaration.members.filter(ts.isSetAccessorDeclaration)) {
    if (setter.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.PrivateKeyword || modifier.kind === ts.SyntaxKind.ProtectedKeyword)) continue;
    const name = setter.name.getText(source);
    const getter = declaration.members.find(member => ts.isGetAccessorDeclaration(member) && member.name.getText(source) === name);
    const attribute = findAttribute(setter) ?? (getter && findAttribute(getter));
    properties.push({ name, ...(attribute ? { attribute } : {}),
      ...(['defaultValue', 'defaultChecked'].includes(name) ? { initialOnly: true } : {}),
      ...(['value', 'checked'].includes(name) && !attribute ? { controlled: true } : {}),
    });
  }
  // Event dispatch is explicit in the current components; fail visibly if conventions change.
  const hasEvents = /\bemitValue\(this,/.test(content);
  components.push({ tag: entry, className: declaration.name.text, properties, hasEvents,
    detail: properties.some(property => property.name === 'checked') ? 'ChidoCheckedDetail' : 'ChidoValueDetail' });
}

let code = `// GENERATED by scripts/generate-react.mjs. Edit the native component API, not this file.\n`;
code += `import { createComponent } from './create-component';\nimport type { HTMLAttributes } from 'react';\nimport type { ChidoValueDetail, ChidoCheckedDetail } from '../components/shared/events';\n\n`;
for (const { tag, className, properties, hasEvents, detail } of components) {
  const element = `${className}Element`;
  code += `import '../components/${tag}/${tag}';\nimport type { ${className} as ${element} } from '../components/${tag}/${tag}';\n`;
  const names = properties.map(property => `'${property.name}'`).join(' | ') || 'never';
  code += `export type ${className}Props = Omit<HTMLAttributes<${element}>, ${names}> & Partial<Pick<${element}, ${names}>>`;
  if (hasEvents) code += ` & {\n  onChidoInput?: (event: CustomEvent<${detail}>) => void;\n  onChidoChange?: (event: CustomEvent<${detail}>) => void;\n}`;
  code += `;\nexport const ${className} = createComponent<${element}, ${className}Props>(\n  '${tag}',\n  ${JSON.stringify(properties, null, 2)},\n  ${hasEvents ? "{ onChidoInput: 'chido-input', onChidoChange: 'chido-change' }" : '{}'},\n);\n\n`;
}
await mkdir(new URL('src/react/', root), { recursive: true });
if (process.argv.includes('--check')) {
  if (await readFile(output, 'utf8').catch(() => '') !== code) {
    throw new Error('React wrappers are stale. Run npm run generate:react.');
  }
} else {
  await writeFile(output, code);
}
console.log(`React wrappers ${process.argv.includes('--check') ? 'verified' : 'generated'} for ${components.length} components.`);
