// GENERATED by scripts/generate-react.mjs. Edit the native component API, not this file.
import { createComponent } from './create-component';
import type { HTMLAttributes } from 'react';
import type { ChidoValueDetail, ChidoCheckedDetail } from '../components/shared/events';

import '../components/chido-alert/chido-alert';
import type { ChidoAlert as ChidoAlertElement } from '../components/chido-alert/chido-alert';
export type ChidoAlertProps = Omit<HTMLAttributes<ChidoAlertElement>, 'variant' | 'message' | 'live'> & Partial<Pick<ChidoAlertElement, 'variant' | 'message' | 'live'>>;
export const ChidoAlert = createComponent<ChidoAlertElement, ChidoAlertProps>(
  'chido-alert',
  [
  {
    "name": "variant",
    "attribute": "variant"
  },
  {
    "name": "message",
    "attribute": "message"
  },
  {
    "name": "live",
    "attribute": "live"
  }
],
  {},
);

import '../components/chido-button/chido-button';
import type { ChidoButton as ChidoButtonElement } from '../components/chido-button/chido-button';
export type ChidoButtonProps = Omit<HTMLAttributes<ChidoButtonElement>, 'disabled'> & Partial<Pick<ChidoButtonElement, 'disabled'>>;
export const ChidoButton = createComponent<ChidoButtonElement, ChidoButtonProps>(
  'chido-button',
  [
  {
    "name": "disabled",
    "attribute": "disabled"
  }
],
  {},
);

import '../components/chido-checkbox/chido-checkbox';
import type { ChidoCheckbox as ChidoCheckboxElement } from '../components/chido-checkbox/chido-checkbox';
export type ChidoCheckboxProps = Omit<HTMLAttributes<ChidoCheckboxElement>, 'controlLabel' | 'controlName' | 'disabled' | 'required' | 'validationText' | 'value' | 'checked' | 'defaultChecked' | 'indeterminate'> & Partial<Pick<ChidoCheckboxElement, 'controlLabel' | 'controlName' | 'disabled' | 'required' | 'validationText' | 'value' | 'checked' | 'defaultChecked' | 'indeterminate'>> & {
  onChidoInput?: (event: CustomEvent<ChidoCheckedDetail>) => void;
  onChidoChange?: (event: CustomEvent<ChidoCheckedDetail>) => void;
};
export const ChidoCheckbox = createComponent<ChidoCheckboxElement, ChidoCheckboxProps>(
  'chido-checkbox',
  [
  {
    "name": "controlLabel",
    "attribute": "control-label"
  },
  {
    "name": "controlName",
    "attribute": "control-name"
  },
  {
    "name": "disabled",
    "attribute": "disabled"
  },
  {
    "name": "required",
    "attribute": "required"
  },
  {
    "name": "validationText",
    "attribute": "validation-text"
  },
  {
    "name": "value",
    "attribute": "value"
  },
  {
    "name": "checked",
    "controlled": true
  },
  {
    "name": "defaultChecked",
    "attribute": "checked",
    "initialOnly": true
  },
  {
    "name": "indeterminate"
  }
],
  { onChidoInput: 'chido-input', onChidoChange: 'chido-change' },
);

import '../components/chido-form-field/chido-form-field';
import type { ChidoFormField as ChidoFormFieldElement } from '../components/chido-form-field/chido-form-field';
export type ChidoFormFieldProps = Omit<HTMLAttributes<ChidoFormFieldElement>, 'controlLabel' | 'helpText' | 'validationText' | 'required' | 'invalid'> & Partial<Pick<ChidoFormFieldElement, 'controlLabel' | 'helpText' | 'validationText' | 'required' | 'invalid'>>;
export const ChidoFormField = createComponent<ChidoFormFieldElement, ChidoFormFieldProps>(
  'chido-form-field',
  [
  {
    "name": "controlLabel",
    "attribute": "control-label"
  },
  {
    "name": "helpText",
    "attribute": "help-text"
  },
  {
    "name": "validationText",
    "attribute": "validation-text"
  },
  {
    "name": "required",
    "attribute": "required"
  },
  {
    "name": "invalid",
    "attribute": "invalid"
  }
],
  {},
);

import '../components/chido-form-summary/chido-form-summary';
import type { ChidoFormSummary as ChidoFormSummaryElement } from '../components/chido-form-summary/chido-form-summary';
export type ChidoFormSummaryProps = Omit<HTMLAttributes<ChidoFormSummaryElement>, 'summaryTitle' | 'errors'> & Partial<Pick<ChidoFormSummaryElement, 'summaryTitle' | 'errors'>>;
export const ChidoFormSummary = createComponent<ChidoFormSummaryElement, ChidoFormSummaryProps>(
  'chido-form-summary',
  [
  {
    "name": "summaryTitle",
    "attribute": "summary-title"
  },
  {
    "name": "errors"
  }
],
  {},
);

import '../components/chido-input/chido-input';
import type { ChidoInput as ChidoInputElement } from '../components/chido-input/chido-input';
export type ChidoInputProps = Omit<HTMLAttributes<ChidoInputElement>, 'inputName' | 'inputLabel' | 'value' | 'defaultValue' | 'disabled' | 'placeholder' | 'required' | 'readOnly' | 'type' | 'autocomplete' | 'minLength' | 'maxLength' | 'pattern' | 'validationText'> & Partial<Pick<ChidoInputElement, 'inputName' | 'inputLabel' | 'value' | 'defaultValue' | 'disabled' | 'placeholder' | 'required' | 'readOnly' | 'type' | 'autocomplete' | 'minLength' | 'maxLength' | 'pattern' | 'validationText'>> & {
  onChidoInput?: (event: CustomEvent<ChidoValueDetail>) => void;
  onChidoChange?: (event: CustomEvent<ChidoValueDetail>) => void;
};
export const ChidoInput = createComponent<ChidoInputElement, ChidoInputProps>(
  'chido-input',
  [
  {
    "name": "inputName",
    "attribute": "input-name"
  },
  {
    "name": "inputLabel",
    "attribute": "input-label"
  },
  {
    "name": "value",
    "controlled": true
  },
  {
    "name": "defaultValue",
    "attribute": "value",
    "initialOnly": true
  },
  {
    "name": "disabled",
    "attribute": "disabled"
  },
  {
    "name": "placeholder",
    "attribute": "placeholder"
  },
  {
    "name": "required",
    "attribute": "required"
  },
  {
    "name": "readOnly",
    "attribute": "readonly"
  },
  {
    "name": "type",
    "attribute": "type"
  },
  {
    "name": "autocomplete",
    "attribute": "autocomplete"
  },
  {
    "name": "minLength",
    "attribute": "minlength"
  },
  {
    "name": "maxLength",
    "attribute": "maxlength"
  },
  {
    "name": "pattern",
    "attribute": "pattern"
  },
  {
    "name": "validationText",
    "attribute": "validation-text"
  }
],
  { onChidoInput: 'chido-input', onChidoChange: 'chido-change' },
);

import '../components/chido-progress/chido-progress';
import type { ChidoProgress as ChidoProgressElement } from '../components/chido-progress/chido-progress';
export type ChidoProgressProps = Omit<HTMLAttributes<ChidoProgressElement>, 'progressLabel' | 'value' | 'max' | 'valueText'> & Partial<Pick<ChidoProgressElement, 'progressLabel' | 'value' | 'max' | 'valueText'>>;
export const ChidoProgress = createComponent<ChidoProgressElement, ChidoProgressProps>(
  'chido-progress',
  [
  {
    "name": "progressLabel",
    "attribute": "progress-label"
  },
  {
    "name": "value",
    "attribute": "value"
  },
  {
    "name": "max",
    "attribute": "max"
  },
  {
    "name": "valueText",
    "attribute": "value-text"
  }
],
  {},
);

import '../components/chido-radio-group/chido-radio-group';
import type { ChidoRadioGroup as ChidoRadioGroupElement } from '../components/chido-radio-group/chido-radio-group';
export type ChidoRadioGroupProps = Omit<HTMLAttributes<ChidoRadioGroupElement>, 'controlLabel' | 'controlName' | 'disabled' | 'required' | 'validationText' | 'value' | 'defaultValue'> & Partial<Pick<ChidoRadioGroupElement, 'controlLabel' | 'controlName' | 'disabled' | 'required' | 'validationText' | 'value' | 'defaultValue'>> & {
  onChidoInput?: (event: CustomEvent<ChidoValueDetail>) => void;
  onChidoChange?: (event: CustomEvent<ChidoValueDetail>) => void;
};
export const ChidoRadioGroup = createComponent<ChidoRadioGroupElement, ChidoRadioGroupProps>(
  'chido-radio-group',
  [
  {
    "name": "controlLabel",
    "attribute": "control-label"
  },
  {
    "name": "controlName",
    "attribute": "control-name"
  },
  {
    "name": "disabled",
    "attribute": "disabled"
  },
  {
    "name": "required",
    "attribute": "required"
  },
  {
    "name": "validationText",
    "attribute": "validation-text"
  },
  {
    "name": "value",
    "controlled": true
  },
  {
    "name": "defaultValue",
    "attribute": "value",
    "initialOnly": true
  }
],
  { onChidoInput: 'chido-input', onChidoChange: 'chido-change' },
);

import '../components/chido-select/chido-select';
import type { ChidoSelect as ChidoSelectElement } from '../components/chido-select/chido-select';
export type ChidoSelectProps = Omit<HTMLAttributes<ChidoSelectElement>, 'controlLabel' | 'controlName' | 'disabled' | 'required' | 'validationText' | 'value' | 'defaultValue'> & Partial<Pick<ChidoSelectElement, 'controlLabel' | 'controlName' | 'disabled' | 'required' | 'validationText' | 'value' | 'defaultValue'>> & {
  onChidoInput?: (event: CustomEvent<ChidoValueDetail>) => void;
  onChidoChange?: (event: CustomEvent<ChidoValueDetail>) => void;
};
export const ChidoSelect = createComponent<ChidoSelectElement, ChidoSelectProps>(
  'chido-select',
  [
  {
    "name": "controlLabel",
    "attribute": "control-label"
  },
  {
    "name": "controlName",
    "attribute": "control-name"
  },
  {
    "name": "disabled",
    "attribute": "disabled"
  },
  {
    "name": "required",
    "attribute": "required"
  },
  {
    "name": "validationText",
    "attribute": "validation-text"
  },
  {
    "name": "value",
    "controlled": true
  },
  {
    "name": "defaultValue",
    "attribute": "value",
    "initialOnly": true
  }
],
  { onChidoInput: 'chido-input', onChidoChange: 'chido-change' },
);

import '../components/chido-textarea/chido-textarea';
import type { ChidoTextarea as ChidoTextareaElement } from '../components/chido-textarea/chido-textarea';
export type ChidoTextareaProps = Omit<HTMLAttributes<ChidoTextareaElement>, 'controlLabel' | 'controlName' | 'disabled' | 'required' | 'validationText' | 'value' | 'defaultValue' | 'placeholder' | 'autocomplete' | 'readOnly' | 'rows' | 'minLength' | 'maxLength'> & Partial<Pick<ChidoTextareaElement, 'controlLabel' | 'controlName' | 'disabled' | 'required' | 'validationText' | 'value' | 'defaultValue' | 'placeholder' | 'autocomplete' | 'readOnly' | 'rows' | 'minLength' | 'maxLength'>> & {
  onChidoInput?: (event: CustomEvent<ChidoValueDetail>) => void;
  onChidoChange?: (event: CustomEvent<ChidoValueDetail>) => void;
};
export const ChidoTextarea = createComponent<ChidoTextareaElement, ChidoTextareaProps>(
  'chido-textarea',
  [
  {
    "name": "controlLabel",
    "attribute": "control-label"
  },
  {
    "name": "controlName",
    "attribute": "control-name"
  },
  {
    "name": "disabled",
    "attribute": "disabled"
  },
  {
    "name": "required",
    "attribute": "required"
  },
  {
    "name": "validationText",
    "attribute": "validation-text"
  },
  {
    "name": "value",
    "controlled": true
  },
  {
    "name": "defaultValue",
    "attribute": "value",
    "initialOnly": true
  },
  {
    "name": "placeholder",
    "attribute": "placeholder"
  },
  {
    "name": "autocomplete",
    "attribute": "autocomplete"
  },
  {
    "name": "readOnly",
    "attribute": "readonly"
  },
  {
    "name": "rows",
    "attribute": "rows"
  },
  {
    "name": "minLength",
    "attribute": "minlength"
  },
  {
    "name": "maxLength",
    "attribute": "maxlength"
  }
],
  { onChidoInput: 'chido-input', onChidoChange: 'chido-change' },
);

